/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mantresh Verma
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form FoodMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        setResizable(false);

        OrderLabel = new javax.swing.JLabel();
        OrderButton = new javax.swing.JButton();
        SearchLabel = new javax.swing.JLabel();
        SearchButton = new javax.swing.JButton();
        LogLabel = new javax.swing.JLabel();
        LogButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Restaurant Management System - Main Menu");
        setMinimumSize(new java.awt.Dimension(1210, 681));
        getContentPane().setLayout(null);

        OrderLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/order.jpg"))); // NOI18N
        getContentPane().add(OrderLabel);
        OrderLabel.setBounds(130, 220, 250, 170);

        OrderButton.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        OrderButton.setText("Place an Order");
        OrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderButtonActionPerformed(evt);
            }
        });
        getContentPane().add(OrderButton);
        OrderButton.setBounds(130, 410, 250, 30);

        SearchLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Seach Food.jpeg"))); // NOI18N
        getContentPane().add(SearchLabel);
        SearchLabel.setBounds(500, 220, 250, 170);

        SearchButton.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        SearchButton.setText("Search Analysis");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SearchButton);
        SearchButton.setBounds(500, 410, 250, 30);

        LogLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Log.jpg"))); // NOI18N
        getContentPane().add(LogLabel);
        LogLabel.setBounds(880, 220, 250, 170);

        LogButton.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        LogButton.setText("Log History");
        LogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogButtonActionPerformed(evt);
            }
        });
        getContentPane().add(LogButton);
        LogButton.setBounds(880, 410, 250, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/r7.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1210, 681);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderButtonActionPerformed
        // TODO add your handling code here:
        OrderMenu OM = new OrderMenu();
        OM.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_OrderButtonActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        // TODO add your handling code here:
        SearchMenu SM = new SearchMenu();
        SM.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void LogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogButtonActionPerformed
        // TODO add your handling code here:
        LogMenu LM = new LogMenu();
        LM.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogButton;
    private javax.swing.JLabel LogLabel;
    private javax.swing.JButton OrderButton;
    private javax.swing.JLabel OrderLabel;
    private javax.swing.JButton SearchButton;
    private javax.swing.JLabel SearchLabel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
