import java.sql.*;
// import java.awt.print.*;
import java.util.Calendar;
import javax.swing.JOptionPane;
import java.util.GregorianCalendar;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mantresh Verma
 */
public class OrderMenu extends javax.swing.JFrame {

    /**
     * Creates new form FoodMenu
     */
    public OrderMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GenderButtonGroup = new javax.swing.ButtonGroup();
        BillMenu = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        BillTextArea = new javax.swing.JTextArea();
        BackgroundLabel2 = new javax.swing.JLabel();
        PlacingOrderPanel = new javax.swing.JPanel();
        CustomerCodePanel = new javax.swing.JPanel();
        CustomerCodeTF = new javax.swing.JTextField();
        BookingDateTF = new javax.swing.JTextField();
        BookingTimeTF = new javax.swing.JTextField();
        BookingDateBtn = new javax.swing.JButton();
        BookingTimeBtn = new javax.swing.JButton();
        GenerateBtn = new javax.swing.JButton();
        CustomerInformationPanel = new javax.swing.JPanel();
        CustomerNameTF = new javax.swing.JTextField();
        MaleRadioBtn = new javax.swing.JRadioButton();
        FemaleRadioBtn = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        ContactNumberTF = new javax.swing.JTextField();
        EmailIDTF = new javax.swing.JTextField();
        SpecialCustCheckBox = new javax.swing.JCheckBox();
        HomeDeliveryCheckBox = new javax.swing.JCheckBox();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AddressTextArea = new javax.swing.JTextArea();
        CustomerOrderPanel = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        CheckBox1 = new javax.swing.JCheckBox();
        ComboBox1 = new javax.swing.JComboBox<>();
        Label1 = new javax.swing.JLabel();
        TF1 = new javax.swing.JTextField();
        CheckBox2 = new javax.swing.JCheckBox();
        ComboBox2 = new javax.swing.JComboBox<>();
        Label2 = new javax.swing.JLabel();
        TF2 = new javax.swing.JTextField();
        CheckBox3 = new javax.swing.JCheckBox();
        ComboBox3 = new javax.swing.JComboBox<>();
        Label3 = new javax.swing.JLabel();
        TF3 = new javax.swing.JTextField();
        CheckBox4 = new javax.swing.JCheckBox();
        ComboBox4 = new javax.swing.JComboBox<>();
        Label4 = new javax.swing.JLabel();
        TF4 = new javax.swing.JTextField();
        CheckBox5 = new javax.swing.JCheckBox();
        ComboBox5 = new javax.swing.JComboBox<>();
        Label5 = new javax.swing.JLabel();
        TF5 = new javax.swing.JTextField();
        CheckBox6 = new javax.swing.JCheckBox();
        ComboBox6 = new javax.swing.JComboBox<>();
        Label6 = new javax.swing.JLabel();
        TF6 = new javax.swing.JTextField();
        CheckBox7 = new javax.swing.JCheckBox();
        ComboBox7 = new javax.swing.JComboBox<>();
        Label7 = new javax.swing.JLabel();
        TF7 = new javax.swing.JTextField();
        CheckBox8 = new javax.swing.JCheckBox();
        ComboBox8 = new javax.swing.JComboBox<>();
        Label8 = new javax.swing.JLabel();
        TF8 = new javax.swing.JTextField();
        ConfigurationPanel = new javax.swing.JPanel();
        ReturnBtn = new javax.swing.JButton();
        ExitBtn = new javax.swing.JButton();
        ResetBtn = new javax.swing.JButton();
        ConfigurationPanel1 = new javax.swing.JPanel();
        TotalBillBtn = new javax.swing.JButton();
        OrderBtn = new javax.swing.JButton();
        TotalLabel = new javax.swing.JLabel();
        ConfigurationPanel2 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        ConfigurationPanel3 = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        BackgroundLabel = new javax.swing.JLabel();

        BillMenu.setTitle("Order Bill");
        BillMenu.setAlwaysOnTop(true);
        BillMenu.setMinimumSize(new java.awt.Dimension(1000, 670));
        BillMenu.setResizable(false);
        BillMenu.setSize(new java.awt.Dimension(1000, 670));
        BillMenu.getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Customer Bill");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BillMenu.getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 100, 530, 40);

        jButton1.setText("Close Bill");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        BillMenu.getContentPane().add(jButton1);
        jButton1.setBounds(410, 560, 130, 30);

        BillTextArea.setColumns(20);
        BillTextArea.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        BillTextArea.setRows(5);
        jScrollPane2.setViewportView(BillTextArea);

        BillMenu.getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(210, 170, 530, 370);

        BackgroundLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/r3.jpg"))); // NOI18N
        BillMenu.getContentPane().add(BackgroundLabel2);
        BackgroundLabel2.setBounds(0, 0, 1000, 670);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Restaurant Management System - Order Menu");
        setMinimumSize(new java.awt.Dimension(1210, 681));
        getContentPane().setLayout(null);

        PlacingOrderPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Placing Food Order Form", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 87, 51))); // NOI18N
        PlacingOrderPanel.setForeground(new java.awt.Color(0, 255, 204));
        PlacingOrderPanel.setOpaque(false);

        CustomerCodePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Generate Customer Code", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16), new java.awt.Color(228, 155, 15))); // NOI18N
        CustomerCodePanel.setForeground(new java.awt.Color(255, 255, 255));
        CustomerCodePanel.setMaximumSize(new java.awt.Dimension(882, 105));
        CustomerCodePanel.setMinimumSize(new java.awt.Dimension(882, 105));
        CustomerCodePanel.setOpaque(false);

        CustomerCodeTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        BookingDateTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        BookingTimeTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        BookingDateBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BookingDateBtn.setText("Booking Date");

        BookingTimeBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BookingTimeBtn.setText("Booking Time");

        GenerateBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        GenerateBtn.setText("Generate");
        GenerateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CustomerCodePanelLayout = new javax.swing.GroupLayout(CustomerCodePanel);
        CustomerCodePanel.setLayout(CustomerCodePanelLayout);
        CustomerCodePanelLayout.setHorizontalGroup(
            CustomerCodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerCodePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GenerateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CustomerCodeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BookingDateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BookingDateTF, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BookingTimeBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BookingTimeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CustomerCodePanelLayout.setVerticalGroup(
            CustomerCodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerCodePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CustomerCodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CustomerCodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BookingDateTF, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BookingDateBtn)
                        .addComponent(CustomerCodeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(GenerateBtn))
                    .addGroup(CustomerCodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BookingTimeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BookingTimeBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CustomerInformationPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Customer Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16), new java.awt.Color(228, 155, 15))); // NOI18N
        CustomerInformationPanel.setOpaque(false);

        CustomerNameTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        CustomerNameTF.setMinimumSize(new java.awt.Dimension(142, 22));
        CustomerNameTF.setPreferredSize(new java.awt.Dimension(142, 22));

        GenderButtonGroup.add(MaleRadioBtn);
        MaleRadioBtn.setForeground(new java.awt.Color(255, 255, 255));
        MaleRadioBtn.setText("Male");
        MaleRadioBtn.setOpaque(false);

        GenderButtonGroup.add(FemaleRadioBtn);
        FemaleRadioBtn.setForeground(new java.awt.Color(255, 255, 255));
        FemaleRadioBtn.setText("Female");
        FemaleRadioBtn.setMinimumSize(new java.awt.Dimension(64, 23));
        FemaleRadioBtn.setOpaque(false);
        FemaleRadioBtn.setPreferredSize(new java.awt.Dimension(64, 23));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Customer Name");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Gender");

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Email ID");

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Contact No");
        jLabel30.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel30FocusGained(evt);
            }
        });

        ContactNumberTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ContactNumberTF.setMinimumSize(new java.awt.Dimension(142, 22));
        ContactNumberTF.setPreferredSize(new java.awt.Dimension(142, 22));

        EmailIDTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        EmailIDTF.setMinimumSize(new java.awt.Dimension(142, 22));
        EmailIDTF.setPreferredSize(new java.awt.Dimension(142, 22));

        SpecialCustCheckBox.setFont(new java.awt.Font("Andalus", 1, 12)); // NOI18N
        SpecialCustCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        SpecialCustCheckBox.setText("Special Customer");
        SpecialCustCheckBox.setOpaque(false);

        HomeDeliveryCheckBox.setFont(new java.awt.Font("Andalus", 1, 12)); // NOI18N
        HomeDeliveryCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        HomeDeliveryCheckBox.setText("Home Delivery");
        HomeDeliveryCheckBox.setOpaque(false);

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Address");

        AddressTextArea.setColumns(20);
        AddressTextArea.setRows(5);
        jScrollPane1.setViewportView(AddressTextArea);

        javax.swing.GroupLayout CustomerInformationPanelLayout = new javax.swing.GroupLayout(CustomerInformationPanel);
        CustomerInformationPanel.setLayout(CustomerInformationPanelLayout);
        CustomerInformationPanelLayout.setHorizontalGroup(
            CustomerInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerInformationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CustomerInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CustomerInformationPanelLayout.createSequentialGroup()
                        .addGroup(CustomerInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CustomerInformationPanelLayout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CustomerNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CustomerInformationPanelLayout.createSequentialGroup()
                                .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                .addGap(51, 51, 51)
                                .addComponent(MaleRadioBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(FemaleRadioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CustomerInformationPanelLayout.createSequentialGroup()
                                .addComponent(SpecialCustCheckBox)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(10, 10, 10))
                    .addGroup(CustomerInformationPanelLayout.createSequentialGroup()
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(CustomerInformationPanelLayout.createSequentialGroup()
                        .addGroup(CustomerInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(CustomerInformationPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(EmailIDTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CustomerInformationPanelLayout.createSequentialGroup()
                                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(CustomerInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(CustomerInformationPanelLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(HomeDeliveryCheckBox))
                                    .addComponent(ContactNumberTF, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())))
            .addGroup(CustomerInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CustomerInformationPanelLayout.createSequentialGroup()
                    .addGap(11, 11, 11)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(186, 186, 186)))
        );
        CustomerInformationPanelLayout.setVerticalGroup(
            CustomerInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerInformationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CustomerInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CustomerNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CustomerInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CustomerInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(MaleRadioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(FemaleRadioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmailIDTF, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CustomerInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ContactNumberTF, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(CustomerInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SpecialCustCheckBox)
                    .addComponent(HomeDeliveryCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CustomerInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(CustomerInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CustomerInformationPanelLayout.createSequentialGroup()
                    .addGap(67, 67, 67)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(245, Short.MAX_VALUE)))
        );

        CustomerOrderPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Customer Order", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16), new java.awt.Color(228, 155, 15))); // NOI18N
        CustomerOrderPanel.setForeground(new java.awt.Color(255, 255, 255));
        CustomerOrderPanel.setOpaque(false);

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel33.setText("Item Name");

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel35.setText("Type");

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel32.setText("Price");

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel36.setText("Quantity");

        CheckBox1.setFont(new java.awt.Font("Andalus", 1, 12)); // NOI18N
        CheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox1.setText("Rice");
        CheckBox1.setOpaque(false);
        CheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBox1ActionPerformed(evt);
            }
        });

        ComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jeera Rice", "Veg Pulav", "Fried Rice", " " }));
        ComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox1ActionPerformed(evt);
            }
        });

        Label1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Label1.setForeground(new java.awt.Color(255, 255, 255));
        Label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label1.setText("0");
        Label1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TF1.setEditable(false);
        TF1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TF1.setText("0");
        TF1.setMinimumSize(new java.awt.Dimension(142, 22));
        TF1.setPreferredSize(new java.awt.Dimension(142, 22));

        CheckBox2.setFont(new java.awt.Font("Andalus", 1, 12)); // NOI18N
        CheckBox2.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox2.setText("Biryani");
        CheckBox2.setOpaque(false);
        CheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBox2ActionPerformed(evt);
            }
        });

        ComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Veg Biryani", "Lamb Biryani", "Chicken Biryani", "Shrimp Biryani", " " }));
        ComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox2ActionPerformed(evt);
            }
        });

        Label2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Label2.setForeground(new java.awt.Color(255, 255, 255));
        Label2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label2.setText("0");
        Label2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TF2.setEditable(false);
        TF2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TF2.setText("0");
        TF2.setMinimumSize(new java.awt.Dimension(142, 22));
        TF2.setPreferredSize(new java.awt.Dimension(142, 22));

        CheckBox3.setFont(new java.awt.Font("Andalus", 1, 12)); // NOI18N
        CheckBox3.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox3.setText("Veg Appetizer");
        CheckBox3.setOpaque(false);
        CheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBox3ActionPerformed(evt);
            }
        });

        ComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Paneer Tikka", "Paneer Pakora", "Veg Manchurian", "Momos", " " }));
        ComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox3ActionPerformed(evt);
            }
        });

        Label3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Label3.setForeground(new java.awt.Color(255, 255, 255));
        Label3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label3.setText("0");
        Label3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TF3.setEditable(false);
        TF3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TF3.setText("0");
        TF3.setMinimumSize(new java.awt.Dimension(142, 22));
        TF3.setPreferredSize(new java.awt.Dimension(142, 22));

        CheckBox4.setFont(new java.awt.Font("Andalus", 1, 12)); // NOI18N
        CheckBox4.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox4.setText("Non-Veg Appetizer");
        CheckBox4.setOpaque(false);
        CheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBox4ActionPerformed(evt);
            }
        });

        ComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tandoori Chicken", "Chicken Tikka", "Chilli Chicken", "Shish Kabob", "Hariyali Chicken", " " }));
        ComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox4ActionPerformed(evt);
            }
        });

        Label4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Label4.setForeground(new java.awt.Color(255, 255, 255));
        Label4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label4.setText("0");
        Label4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TF4.setEditable(false);
        TF4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TF4.setText("0");
        TF4.setMinimumSize(new java.awt.Dimension(142, 22));
        TF4.setPreferredSize(new java.awt.Dimension(142, 22));

        CheckBox5.setFont(new java.awt.Font("Andalus", 1, 12)); // NOI18N
        CheckBox5.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox5.setText("Chapati");
        CheckBox5.setOpaque(false);
        CheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBox5ActionPerformed(evt);
            }
        });

        ComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Naan", "Tandoori Roti", "Laccha Paratha", "Makhani Roti" }));
        ComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox5ActionPerformed(evt);
            }
        });

        Label5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Label5.setForeground(new java.awt.Color(255, 255, 255));
        Label5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label5.setText("0");
        Label5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TF5.setEditable(false);
        TF5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TF5.setText("0");
        TF5.setMinimumSize(new java.awt.Dimension(142, 22));
        TF5.setPreferredSize(new java.awt.Dimension(142, 22));

        CheckBox6.setFont(new java.awt.Font("Andalus", 1, 12)); // NOI18N
        CheckBox6.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox6.setText("Desserts");
        CheckBox6.setOpaque(false);
        CheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBox6ActionPerformed(evt);
            }
        });

        ComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gulab Jamun", "Rasmalai", "Kheer" }));
        ComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox6ActionPerformed(evt);
            }
        });

        Label6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Label6.setForeground(new java.awt.Color(255, 255, 255));
        Label6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label6.setText("0");
        Label6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TF6.setEditable(false);
        TF6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TF6.setText("0");
        TF6.setMinimumSize(new java.awt.Dimension(142, 22));
        TF6.setPreferredSize(new java.awt.Dimension(142, 22));

        CheckBox7.setFont(new java.awt.Font("Andalus", 1, 12)); // NOI18N
        CheckBox7.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox7.setText("Drinks");
        CheckBox7.setOpaque(false);
        CheckBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBox7ActionPerformed(evt);
            }
        });

        ComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lassi", "Sharbat", "Aamras", "Thandai", " " }));
        ComboBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox7ActionPerformed(evt);
            }
        });

        Label7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Label7.setForeground(new java.awt.Color(255, 255, 255));
        Label7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label7.setText("0");
        Label7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TF7.setEditable(false);
        TF7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TF7.setText("0");
        TF7.setMinimumSize(new java.awt.Dimension(142, 22));
        TF7.setPreferredSize(new java.awt.Dimension(142, 22));

        CheckBox8.setFont(new java.awt.Font("Andalus", 1, 12)); // NOI18N
        CheckBox8.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox8.setText("Street Food");
        CheckBox8.setOpaque(false);
        CheckBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBox8ActionPerformed(evt);
            }
        });

        ComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pani Puri", "Bhel Puri", "Pav Bhaji", "Dahi Vada", "Samosa" }));
        ComboBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox8ActionPerformed(evt);
            }
        });

        Label8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Label8.setForeground(new java.awt.Color(255, 255, 255));
        Label8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label8.setText("0");
        Label8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TF8.setEditable(false);
        TF8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TF8.setText("0");
        TF8.setMinimumSize(new java.awt.Dimension(142, 22));
        TF8.setPreferredSize(new java.awt.Dimension(142, 22));

        javax.swing.GroupLayout CustomerOrderPanelLayout = new javax.swing.GroupLayout(CustomerOrderPanel);
        CustomerOrderPanel.setLayout(CustomerOrderPanelLayout);
        CustomerOrderPanelLayout.setHorizontalGroup(
            CustomerOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerOrderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CustomerOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CustomerOrderPanelLayout.createSequentialGroup()
                        .addComponent(CheckBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Label5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TF5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CustomerOrderPanelLayout.createSequentialGroup()
                        .addComponent(CheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TF1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CustomerOrderPanelLayout.createSequentialGroup()
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CustomerOrderPanelLayout.createSequentialGroup()
                        .addComponent(CheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Label2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TF2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CustomerOrderPanelLayout.createSequentialGroup()
                        .addComponent(CheckBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Label3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TF3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CustomerOrderPanelLayout.createSequentialGroup()
                        .addComponent(CheckBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Label4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TF4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CustomerOrderPanelLayout.createSequentialGroup()
                        .addComponent(CheckBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Label6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TF6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CustomerOrderPanelLayout.createSequentialGroup()
                        .addComponent(CheckBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Label7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TF7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CustomerOrderPanelLayout.createSequentialGroup()
                        .addComponent(CheckBox8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Label8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TF8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        CustomerOrderPanelLayout.setVerticalGroup(
            CustomerOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerOrderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CustomerOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CustomerOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckBox1)
                    .addComponent(ComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TF1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CustomerOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckBox2)
                    .addComponent(ComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TF2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CustomerOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckBox3)
                    .addComponent(ComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TF3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CustomerOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckBox4)
                    .addComponent(ComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TF4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CustomerOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckBox5)
                    .addComponent(ComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TF5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CustomerOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckBox6)
                    .addComponent(ComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TF6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CustomerOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckBox7)
                    .addComponent(ComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TF7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CustomerOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckBox8)
                    .addComponent(ComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TF8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ConfigurationPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Configurations", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16), new java.awt.Color(228, 155, 15))); // NOI18N
        ConfigurationPanel.setMaximumSize(new java.awt.Dimension(577, 108));
        ConfigurationPanel.setMinimumSize(new java.awt.Dimension(577, 108));
        ConfigurationPanel.setOpaque(false);

        ReturnBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ReturnBtn.setText("Return To Home");
        ReturnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnBtnActionPerformed(evt);
            }
        });

        ExitBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ExitBtn.setText("Exit");
        ExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtnActionPerformed(evt);
            }
        });

        ResetBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ResetBtn.setText("Reset");
        ResetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ConfigurationPanelLayout = new javax.swing.GroupLayout(ConfigurationPanel);
        ConfigurationPanel.setLayout(ConfigurationPanelLayout);
        ConfigurationPanelLayout.setHorizontalGroup(
            ConfigurationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConfigurationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ConfigurationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ReturnBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConfigurationPanelLayout.createSequentialGroup()
                        .addComponent(ResetBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ExitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ConfigurationPanelLayout.setVerticalGroup(
            ConfigurationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConfigurationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ConfigurationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ExitBtn)
                    .addComponent(ResetBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ReturnBtn)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        ConfigurationPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Configurations", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16), new java.awt.Color(228, 155, 15))); // NOI18N
        ConfigurationPanel1.setMaximumSize(new java.awt.Dimension(577, 108));
        ConfigurationPanel1.setMinimumSize(new java.awt.Dimension(577, 108));
        ConfigurationPanel1.setOpaque(false);

        TotalBillBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TotalBillBtn.setText("Total Bill");
        TotalBillBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalBillBtnActionPerformed(evt);
            }
        });

        OrderBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        OrderBtn.setText("Place Food Order");
        OrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderBtnActionPerformed(evt);
            }
        });

        TotalLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TotalLabel.setForeground(new java.awt.Color(255, 255, 255));
        TotalLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TotalLabel.setText("0");
        TotalLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout ConfigurationPanel1Layout = new javax.swing.GroupLayout(ConfigurationPanel1);
        ConfigurationPanel1.setLayout(ConfigurationPanel1Layout);
        ConfigurationPanel1Layout.setHorizontalGroup(
            ConfigurationPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConfigurationPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ConfigurationPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(OrderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConfigurationPanel1Layout.createSequentialGroup()
                        .addComponent(TotalBillBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ConfigurationPanel1Layout.setVerticalGroup(
            ConfigurationPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConfigurationPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ConfigurationPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TotalBillBtn))
                .addGap(11, 11, 11)
                .addComponent(OrderBtn)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        ConfigurationPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("."));
        ConfigurationPanel2.setMaximumSize(new java.awt.Dimension(577, 108));
        ConfigurationPanel2.setMinimumSize(new java.awt.Dimension(577, 108));
        ConfigurationPanel2.setOpaque(false);

        jLabel46.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rice.jpg"))); // NOI18N

        jLabel47.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biryani.jpg"))); // NOI18N

        jLabel48.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paneer.jpg"))); // NOI18N

        jLabel49.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/roti.jpg"))); // NOI18N

        javax.swing.GroupLayout ConfigurationPanel2Layout = new javax.swing.GroupLayout(ConfigurationPanel2);
        ConfigurationPanel2.setLayout(ConfigurationPanel2Layout);
        ConfigurationPanel2Layout.setHorizontalGroup(
            ConfigurationPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConfigurationPanel2Layout.createSequentialGroup()
                .addGroup(ConfigurationPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(ConfigurationPanel2Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(ConfigurationPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(364, Short.MAX_VALUE))
        );
        ConfigurationPanel2Layout.setVerticalGroup(
            ConfigurationPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConfigurationPanel2Layout.createSequentialGroup()
                .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        ConfigurationPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("."));
        ConfigurationPanel3.setMaximumSize(new java.awt.Dimension(577, 108));
        ConfigurationPanel3.setMinimumSize(new java.awt.Dimension(577, 108));
        ConfigurationPanel3.setOpaque(false);

        jLabel51.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dessert.jpg"))); // NOI18N

        jLabel52.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pani_puri.jpg"))); // NOI18N

        jLabel53.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drinks.jpg"))); // NOI18N

        javax.swing.GroupLayout ConfigurationPanel3Layout = new javax.swing.GroupLayout(ConfigurationPanel3);
        ConfigurationPanel3.setLayout(ConfigurationPanel3Layout);
        ConfigurationPanel3Layout.setHorizontalGroup(
            ConfigurationPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConfigurationPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ConfigurationPanel3Layout.setVerticalGroup(
            ConfigurationPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConfigurationPanel3Layout.createSequentialGroup()
                .addGroup(ConfigurationPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel51, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel53, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel52, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout PlacingOrderPanelLayout = new javax.swing.GroupLayout(PlacingOrderPanel);
        PlacingOrderPanel.setLayout(PlacingOrderPanelLayout);
        PlacingOrderPanelLayout.setHorizontalGroup(
            PlacingOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlacingOrderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PlacingOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PlacingOrderPanelLayout.createSequentialGroup()
                        .addComponent(ConfigurationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ConfigurationPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ConfigurationPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PlacingOrderPanelLayout.createSequentialGroup()
                        .addGroup(PlacingOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CustomerCodePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(PlacingOrderPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(CustomerInformationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(CustomerOrderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addComponent(ConfigurationPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        PlacingOrderPanelLayout.setVerticalGroup(
            PlacingOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlacingOrderPanelLayout.createSequentialGroup()
                .addGroup(PlacingOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PlacingOrderPanelLayout.createSequentialGroup()
                        .addComponent(CustomerCodePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PlacingOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CustomerOrderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CustomerInformationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(ConfigurationPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PlacingOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ConfigurationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ConfigurationPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ConfigurationPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(PlacingOrderPanel);
        PlacingOrderPanel.setBounds(20, 20, 1160, 630);

        BackgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/r7.jpg"))); // NOI18N
        getContentPane().add(BackgroundLabel);
        BackgroundLabel.setBounds(0, 0, 1210, 681);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReturnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnBtnActionPerformed
        // TODO add your handling code here:
        MainMenu MM = new MainMenu();
        MM.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ReturnBtnActionPerformed

    private void ExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitBtnActionPerformed

    private void ResetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetBtnActionPerformed
        // TODO add your handling code here:
        OrderMenu OM = new OrderMenu();
        OM.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ResetBtnActionPerformed

    private void GenerateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateBtnActionPerformed
        // TODO add your handling code here:
//        String months[] = { "January", "February", "March", "April",   
//                           "May", "June", "July", "August",   
//                           "September", "October", "November", "December" }; 
        
        // In gregorian calendar month is started from 0
        // so for May month will be 04 not 05
        Calendar cal = new GregorianCalendar();
        int Year = cal.get(Calendar.YEAR);
        int Month = cal.get(Calendar.MONTH);
//        String Month = months[cal.get(Calendar.MONTH)];
        int Date = cal.get(Calendar.DATE);
        BookingDateTF.setText(""+Year+"-"+Month+"-"+Date);
                
        int hour = cal.get(Calendar.HOUR);
        int min = cal.get(Calendar.MINUTE);
        int sec = cal.get(Calendar.SECOND);
        int AM_PM = cal.get(Calendar.AM_PM);
        String day_night = "";
        int bit = 0 ;
        if( AM_PM == 1 ) 
        { 
            day_night = "PM"; 
            bit = 1; 
        }
        else 
        {
            day_night = "AM";
            bit = 0;
        }
        BookingTimeTF.setText(""+hour+" : "+min+" : "+sec+" : "+day_night);
        CustomerCodeTF.setText(""+Year+Month+Date+hour+min+sec+bit);                
    }//GEN-LAST:event_GenerateBtnActionPerformed

    private void OrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderBtnActionPerformed
        // TODO add your handling code here:
        try {
                Class.forName("java.sql.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/restaurant","root","root");
                Statement stmt = con.createStatement();

                long Customer_Code = Long.parseLong(CustomerCodeTF.getText());
                String Date = BookingDateTF.getText();
                String Time = BookingTimeTF.getText();
                    
                String Name = CustomerNameTF.getText();
                String EmailID = EmailIDTF.getText();
                long Contact_No = Long.parseLong(ContactNumberTF.getText());
                
                String Address = null;
                String Home_Delivery = "No";
                if(HomeDeliveryCheckBox.isSelected() == true)
                {
                    Address = AddressTextArea.getText();
                    Home_Delivery = "Yes";
                }

                String Gender = "";
                if (MaleRadioBtn.isSelected() == true) Gender = "Male";
                else Gender = "Female";

                String Special_Customer = "";
                if (SpecialCustCheckBox.isSelected()==true) Special_Customer = "Yes";
                else Special_Customer = "No";
                
                int q1 = Integer.parseInt(TF1.getText());
                int q2 = Integer.parseInt(TF2.getText());
                int q3 = Integer.parseInt(TF3.getText());
                int q4 = Integer.parseInt(TF4.getText());
                int q5 = Integer.parseInt(TF5.getText());
                int q6 = Integer.parseInt(TF6.getText());
                int q7 = Integer.parseInt(TF7.getText());
                int q8 = Integer.parseInt(TF8.getText());
                
                String Rice_Type = "";
                String Biryani_Type = "";
                String Veg_Appetizer_Type = "";
                String Non_Veg_Appetizer_Type = "" ;
                String Chapati_Type = "";
                String Desserts_Type = "";
                String Drinks_Type = "";
                String Street_Food_Type = "" ;
                
                int a = ComboBox1.getSelectedIndex();
                switch(a) {
                    case 0 : Rice_Type = "Jeera Rice";
                    case 1 : Rice_Type = "Veg Pulav";
                    case 2 : Rice_Type = "Fried Rice";
                }
                int b = ComboBox2.getSelectedIndex();
                switch(b) {
                    case 0 : Biryani_Type = "Veg Biryani";
                    case 1 : Biryani_Type = "Lamb Biryani";
                    case 2 : Biryani_Type = "Chicken Biryani";
                    case 3 : Biryani_Type = "Shrimp Biryani";
                }
                int c = ComboBox3.getSelectedIndex();
                switch(c) {
                    case 0 : Veg_Appetizer_Type = "Paneer Tikka";
                    case 1 : Veg_Appetizer_Type = "Paneer Pakora";
                    case 2 : Veg_Appetizer_Type = "Veg Manchurian";
                    case 3 : Veg_Appetizer_Type = "Momos";
                }
                int d = ComboBox4.getSelectedIndex();
                switch(d) {
                    case 0 : Non_Veg_Appetizer_Type = "Tandoori Chicken";
                    case 1 : Non_Veg_Appetizer_Type = "Chicken Tikka";
                    case 2 : Non_Veg_Appetizer_Type = "Chilli Chicken";
                    case 3 : Non_Veg_Appetizer_Type = "Shish Kabob";
                    case 4 : Non_Veg_Appetizer_Type = "Hariyali Chicken";
                }
                int e = ComboBox5.getSelectedIndex();
                switch(e) {
                    case 0 : Chapati_Type = "Naan";
                    case 1 : Chapati_Type = "Tandoori Roti";
                    case 2 : Chapati_Type = "Laccha Paratha";
                    case 3 : Chapati_Type = "Makhani Roti";
                }
                int f = ComboBox6.getSelectedIndex();
                switch(f) {
                    case 0 : Desserts_Type = "Gulab Jamun";
                    case 1 : Desserts_Type = "Rasmalai";
                    case 2 : Desserts_Type = "Kheer";
                }
                int g = ComboBox7.getSelectedIndex();
                switch(g) {
                    case 0 : Drinks_Type = "Lassi";
                    case 1 : Drinks_Type = "Sharbat";
                    case 2 : Drinks_Type = "Aamras";
                    case 3 : Drinks_Type = "Thandai";
                }
                int h = ComboBox8.getSelectedIndex();
                switch(h) {
                    case 0 : Street_Food_Type = "Pani Puri";
                    case 1 : Street_Food_Type = "Bhel Puri";
                    case 2 : Street_Food_Type = "Pav Bhaji";
                    case 3 : Street_Food_Type = "Dahi Vada";
                    case 4 : Street_Food_Type = "Samosa";
                }        
                
                
                float Total_Bill = Float.parseFloat(TotalLabel.getText());
                
                String save = "insert into food_order values("+Customer_Code+",'"+Date+"','"+Time+"','"+Name+"','"
                        +Gender+"','"+EmailID+"',"+Contact_No+",'"+Special_Customer+"','"+Home_Delivery+"','"
                        +Address+"','"+Rice_Type+"',"+q1+",'"+Biryani_Type+"',"+q2+",'"+Veg_Appetizer_Type+"',"
                        +q3+",'"+Non_Veg_Appetizer_Type+"',"+q4+",'"+Chapati_Type+"',"+q5+",'"+Desserts_Type+"',"
                        +q6+",'"+Drinks_Type+"',"+q7+",'"+Street_Food_Type+"',"+q8+","+Total_Bill+")" ;
                stmt.executeUpdate(save);
                
                JOptionPane.showMessageDialog(this,"Reservation Details Data Saved Successfully","Information",1);
                
                
                BillTextArea.append("- - - - - - - - - - - - - - - - - - - - - - -"
                        +"\n"+"**Welcome to Our Restaurant**"
                        +"\n"+"- - - - - - - - - - - - - - - - - - - - - - -"
                        +"\n\n"+"Customer Code : "+Customer_Code
                        +"\n"+"Order Date : "     +Date
                        +"\n"+"Order Time : "     +Time
                        +"\n"+"Customer Name : "  +Name
                        +"\n"+"Gender : "         +Gender
                        +"\n"+"Email ID : "       +EmailID
                        +"\n"+"Contact Number : " +Contact_No
                        +"\n\n"+"- - - - - - - - - - - - - - - - - - - - - - -"
                        +"\n"+"Item Name        Quantity        Amount"
                        +"\n"+"- - - - - - - - - - - - - - - - - - - - - - -"
                        );
                
                if(CheckBox1.isSelected() == true)
                    BillTextArea.append("\n"+Rice_Type+"        "+q1+"        "+"80");
                if(CheckBox2.isSelected() == true)
                    BillTextArea.append("\n"+Biryani_Type+"        "+q2+"        "+"100");
                if(CheckBox3.isSelected() == true)
                    BillTextArea.append("\n"+Veg_Appetizer_Type+"        "+q3+"        "+"150");
                if(CheckBox4.isSelected() == true)
                    BillTextArea.append("\n"+Non_Veg_Appetizer_Type+"        "+q4+"        "+"200");
                if(CheckBox5.isSelected() == true)
                    BillTextArea.append("\n"+Chapati_Type+"        "+q5+"        "+"20");
                if(CheckBox6.isSelected() == true)
                    BillTextArea.append("\n"+Desserts_Type+"        "+q6+"        "+"40");
                if(CheckBox7.isSelected() == true)
                    BillTextArea.append("\n"+Drinks_Type+"        "+q7+"        "+"50");
                if(CheckBox8.isSelected() == true)
                    BillTextArea.append("\n"+Street_Food_Type+"        "+q8+"        "+"30");
                
                BillTextArea.append("\n\n- - - - - - - - - - - - - - - - - - - - - - -"
                        +"\n"+"Total Bill Amount : "+Total_Bill
                        +"\n"+"- - - - - - - - - - - - - - - - - - - - - - -"
                        );
                
                
                BillMenu.setVisible(true);
            }catch(Exception e) {
                JOptionPane.showMessageDialog(this,e.getMessage(),"Error",0);
            }
        
    }//GEN-LAST:event_OrderBtnActionPerformed

    private void TotalBillBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalBillBtnActionPerformed
        // TODO add your handling code here:
        int p1 = Integer.parseInt(Label1.getText());
        int p2 = Integer.parseInt(Label2.getText());
        int p3 = Integer.parseInt(Label3.getText());
        int p4 = Integer.parseInt(Label4.getText());
        int p5 = Integer.parseInt(Label5.getText());
        int p6 = Integer.parseInt(Label6.getText());
        int p7 = Integer.parseInt(Label7.getText());
        int p8 = Integer.parseInt(Label8.getText());
        
        int q1 = Integer.parseInt(TF1.getText());
        int q2 = Integer.parseInt(TF2.getText());
        int q3 = Integer.parseInt(TF3.getText());
        int q4 = Integer.parseInt(TF4.getText());
        int q5 = Integer.parseInt(TF5.getText());
        int q6 = Integer.parseInt(TF6.getText());
        int q7 = Integer.parseInt(TF7.getText());
        int q8 = Integer.parseInt(TF8.getText());
        
        float Total_Bill = ( (p1*q1)+(p2*q2)+(p3*q3)+(p4*q4)+(p5*q5)+(p6*q6)+(p7*q7)+(p8*q8) );
        if(SpecialCustCheckBox.isSelected() == true)
            Total_Bill = (float) (Total_Bill * 0.9);
        if(HomeDeliveryCheckBox.isSelected() == true)
            Total_Bill = Total_Bill + 30 ;
        TotalLabel.setText(""+Total_Bill);
    }//GEN-LAST:event_TotalBillBtnActionPerformed

    private void CheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBox1ActionPerformed
        // TODO add your handling code here:
        if(CheckBox1.isSelected() == true)
            TF1.setEditable(true);
        if(CheckBox1.isSelected() == false)
            TF1.setEditable(false);
    }//GEN-LAST:event_CheckBox1ActionPerformed

    private void CheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBox2ActionPerformed
        // TODO add your handling code here:
        if(CheckBox2.isSelected() == true)
            TF2.setEditable(true);
        if(CheckBox2.isSelected() == false)
            TF2.setEditable(false);
    }//GEN-LAST:event_CheckBox2ActionPerformed

    private void CheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBox3ActionPerformed
        // TODO add your handling code here:
        if(CheckBox3.isSelected() == true)
            TF3.setEditable(true);
        if(CheckBox3.isSelected() == false)
            TF3.setEditable(false);
    }//GEN-LAST:event_CheckBox3ActionPerformed

    private void CheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBox4ActionPerformed
        // TODO add your handling code here:
        if(CheckBox4.isSelected() == true)
            TF4.setEditable(true);
        if(CheckBox4.isSelected() == false)
            TF4.setEditable(false);
    }//GEN-LAST:event_CheckBox4ActionPerformed

    private void CheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBox5ActionPerformed
        // TODO add your handling code here:
        if(CheckBox5.isSelected() == true)
            TF5.setEditable(true);
        if(CheckBox5.isSelected() == false)
            TF5.setEditable(false);
    }//GEN-LAST:event_CheckBox5ActionPerformed

    private void CheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBox6ActionPerformed
        // TODO add your handling code here:
        if(CheckBox6.isSelected() == true)
            TF6.setEditable(true);
        if(CheckBox6.isSelected() == false)
            TF6.setEditable(false);
    }//GEN-LAST:event_CheckBox6ActionPerformed

    private void CheckBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBox7ActionPerformed
        // TODO add your handling code here:
        if(CheckBox7.isSelected() == true)
            TF7.setEditable(true);
        if(CheckBox7.isSelected() == false)
            TF7.setEditable(false);
    }//GEN-LAST:event_CheckBox7ActionPerformed

    private void CheckBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBox8ActionPerformed
        // TODO add your handling code here:
        if(CheckBox8.isSelected() == true)
            TF8.setEditable(true);
        if(CheckBox8.isSelected() == false)
            TF8.setEditable(false);
    }//GEN-LAST:event_CheckBox8ActionPerformed

    private void ComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox1ActionPerformed
        // TODO add your handling code here:
        int a = ComboBox1.getSelectedIndex();
        switch(a) {
            case 0 : 
            case 1 : 
            case 2 : Label1.setText("80");
        }
    }//GEN-LAST:event_ComboBox1ActionPerformed

    private void ComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox2ActionPerformed
        // TODO add your handling code here:
        int b = ComboBox2.getSelectedIndex();
        switch(b) {
            case 0 : 
            case 1 : 
            case 2 :
            case 3 : Label2.setText("100");
        }
    }//GEN-LAST:event_ComboBox2ActionPerformed

    private void ComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox3ActionPerformed
        // TODO add your handling code here:
        int c = ComboBox3.getSelectedIndex();
        switch(c) {
            case 0 : 
            case 1 : 
            case 2 :
            case 3 : Label3.setText("150");
        }
    }//GEN-LAST:event_ComboBox3ActionPerformed

    private void ComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox4ActionPerformed
        // TODO add your handling code here:
        int d = ComboBox4.getSelectedIndex();
        switch(d) {
            case 0 : 
            case 1 : 
            case 2 : 
            case 3 : 
            case 4 : Label4.setText("200");
        }
    }//GEN-LAST:event_ComboBox4ActionPerformed

    private void ComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox5ActionPerformed
        // TODO add your handling code here:
        int e = ComboBox5.getSelectedIndex();
        switch(e) {
            case 0 : 
            case 1 :
            case 2 :
            case 3 : Label5.setText("20");
        }
    }//GEN-LAST:event_ComboBox5ActionPerformed

    private void ComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox6ActionPerformed
        // TODO add your handling code here:
        int f = ComboBox6.getSelectedIndex();
        switch(f) {
            case 0 : 
            case 1 : 
            case 2 : Label6.setText("40");
        }
    }//GEN-LAST:event_ComboBox6ActionPerformed

    private void ComboBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox7ActionPerformed
        // TODO add your handling code here:
        int g = ComboBox7.getSelectedIndex();
        switch(g) {
            case 0 : 
            case 1 : 
            case 2 : 
            case 3 : Label7.setText("50");
        }
    }//GEN-LAST:event_ComboBox7ActionPerformed

    private void ComboBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox8ActionPerformed
        // TODO add your handling code here:
        int h = ComboBox8.getSelectedIndex();
        switch(h) {
            case 0 : 
            case 1 : 
            case 2 : 
            case 3 : 
            case 4 : Label8.setText("30");
        }
    }//GEN-LAST:event_ComboBox8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        BillMenu.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel30FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel30FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel30FocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AddressTextArea;
    private javax.swing.JLabel BackgroundLabel;
    private javax.swing.JLabel BackgroundLabel2;
    private javax.swing.JFrame BillMenu;
    private javax.swing.JTextArea BillTextArea;
    private javax.swing.JButton BookingDateBtn;
    private javax.swing.JTextField BookingDateTF;
    private javax.swing.JButton BookingTimeBtn;
    private javax.swing.JTextField BookingTimeTF;
    private javax.swing.JCheckBox CheckBox1;
    private javax.swing.JCheckBox CheckBox2;
    private javax.swing.JCheckBox CheckBox3;
    private javax.swing.JCheckBox CheckBox4;
    private javax.swing.JCheckBox CheckBox5;
    private javax.swing.JCheckBox CheckBox6;
    private javax.swing.JCheckBox CheckBox7;
    private javax.swing.JCheckBox CheckBox8;
    private javax.swing.JComboBox<String> ComboBox1;
    private javax.swing.JComboBox<String> ComboBox2;
    private javax.swing.JComboBox<String> ComboBox3;
    private javax.swing.JComboBox<String> ComboBox4;
    private javax.swing.JComboBox<String> ComboBox5;
    private javax.swing.JComboBox<String> ComboBox6;
    private javax.swing.JComboBox<String> ComboBox7;
    private javax.swing.JComboBox<String> ComboBox8;
    private javax.swing.JPanel ConfigurationPanel;
    private javax.swing.JPanel ConfigurationPanel1;
    private javax.swing.JPanel ConfigurationPanel2;
    private javax.swing.JPanel ConfigurationPanel3;
    private javax.swing.JTextField ContactNumberTF;
    private javax.swing.JPanel CustomerCodePanel;
    private javax.swing.JTextField CustomerCodeTF;
    private javax.swing.JPanel CustomerInformationPanel;
    private javax.swing.JTextField CustomerNameTF;
    private javax.swing.JPanel CustomerOrderPanel;
    private javax.swing.JTextField EmailIDTF;
    private javax.swing.JButton ExitBtn;
    private javax.swing.JRadioButton FemaleRadioBtn;
    private javax.swing.ButtonGroup GenderButtonGroup;
    private javax.swing.JButton GenerateBtn;
    private javax.swing.JCheckBox HomeDeliveryCheckBox;
    private javax.swing.JLabel Label1;
    private javax.swing.JLabel Label2;
    private javax.swing.JLabel Label3;
    private javax.swing.JLabel Label4;
    private javax.swing.JLabel Label5;
    private javax.swing.JLabel Label6;
    private javax.swing.JLabel Label7;
    private javax.swing.JLabel Label8;
    private javax.swing.JRadioButton MaleRadioBtn;
    private javax.swing.JButton OrderBtn;
    private javax.swing.JPanel PlacingOrderPanel;
    private javax.swing.JButton ResetBtn;
    private javax.swing.JButton ReturnBtn;
    private javax.swing.JCheckBox SpecialCustCheckBox;
    private javax.swing.JTextField TF1;
    private javax.swing.JTextField TF2;
    private javax.swing.JTextField TF3;
    private javax.swing.JTextField TF4;
    private javax.swing.JTextField TF5;
    private javax.swing.JTextField TF6;
    private javax.swing.JTextField TF7;
    private javax.swing.JTextField TF8;
    private javax.swing.JButton TotalBillBtn;
    private javax.swing.JLabel TotalLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
