import java.sql.*;
import java.util.Calendar;
import javax.swing.table.*;
import javax.swing.JOptionPane;
import java.util.GregorianCalendar;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mantresh Verma
 */
public class SearchMenu extends javax.swing.JFrame {

    /**
     * Creates new form FoodMenu
     */
    public SearchMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        LogBtn = new javax.swing.JButton();
        ReturnBtn = new javax.swing.JButton();
        TF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        LogBtn1 = new javax.swing.JButton();
        LogBtn2 = new javax.swing.JButton();
        LogBtn3 = new javax.swing.JButton();
        LogBtn4 = new javax.swing.JButton();
        BackgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Restaurant Management System - Search Menu");
        setMinimumSize(new java.awt.Dimension(1001, 661));
        setPreferredSize(new java.awt.Dimension(1001, 661));
        getContentPane().setLayout(null);

        jScrollPane4.setMaximumSize(new java.awt.Dimension(3000, 500));
        jScrollPane4.setMinimumSize(new java.awt.Dimension(600, 300));
        jScrollPane4.setPreferredSize(new java.awt.Dimension(600, 300));

        jTable1.setBackground(new java.awt.Color(255, 255, 240));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer Code", "DATE", "TIME", "NAME", "GENDER", "Email ID", "Contact No", "SPECIAL CUST", "TOTAL BILL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class, java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setMaximumSize(new java.awt.Dimension(550, 300));
        jTable1.setMinimumSize(new java.awt.Dimension(550, 300));
        jTable1.setPreferredSize(new java.awt.Dimension(550, 300));
        jTable1.setRowHeight(20);
        jScrollPane4.setViewportView(jTable1);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(50, 210, 870, 340);

        LogBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LogBtn.setText("Exit");
        LogBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogBtnActionPerformed(evt);
            }
        });
        getContentPane().add(LogBtn);
        LogBtn.setBounds(620, 120, 130, 23);

        ReturnBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ReturnBtn.setText("Return To Home");
        ReturnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnBtnActionPerformed(evt);
            }
        });
        getContentPane().add(ReturnBtn);
        ReturnBtn.setBounds(60, 120, 190, 23);

        TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFActionPerformed(evt);
            }
        });
        getContentPane().add(TF);
        TF.setBounds(150, 80, 100, 26);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Enter Value");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 80, 90, 20);

        LogBtn1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LogBtn1.setText("Search By Year");
        LogBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogBtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(LogBtn1);
        LogBtn1.setBounds(280, 120, 290, 23);

        LogBtn2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LogBtn2.setText("Search by Date");
        LogBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogBtn2ActionPerformed(evt);
            }
        });
        getContentPane().add(LogBtn2);
        LogBtn2.setBounds(280, 80, 130, 23);

        LogBtn3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LogBtn3.setText("Search by Month");
        LogBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogBtn3ActionPerformed(evt);
            }
        });
        getContentPane().add(LogBtn3);
        LogBtn3.setBounds(430, 80, 140, 23);

        LogBtn4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LogBtn4.setText("Reset");
        LogBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogBtn4ActionPerformed(evt);
            }
        });
        getContentPane().add(LogBtn4);
        LogBtn4.setBounds(620, 80, 130, 23);

        BackgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/r3.jpg"))); // NOI18N
        getContentPane().add(BackgroundLabel);
        BackgroundLabel.setBounds(0, 0, 1000, 660);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_LogBtnActionPerformed

    private void ReturnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnBtnActionPerformed
        // TODO add your handling code here:
        MainMenu MM =  new MainMenu();
        MM.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ReturnBtnActionPerformed

    private void LogBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogBtn1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/restaurant","root","root");
            Statement stmt = con.createStatement();
            int n = Integer.parseInt(TF.getText());
            String LOG = "select * from food_order where year(date) = "+n;
            ResultSet rs = stmt.executeQuery(LOG);

            while (rs.next())
            {
                long A = rs.getLong("Customer_Code");
                String B = rs.getString("Date");
                String C = rs.getString("Time");
                String D = rs.getString("Name");
                String E = rs.getString("Gender");
                String F = rs.getString("EmailId");
                long G = rs.getLong("Contact_No");
                String H = rs.getString("Special_Customer");
                float I = rs.getFloat("Total_Bill");

                Object [] data = { A,B,C,D,E,F,G,H,I } ;
                dtm.addRow(data);
            }
                JOptionPane.showMessageDialog(null,"Customer Log Successfully Searched","Information",1);
            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"No Data Found","Error",0);
        }
    }//GEN-LAST:event_LogBtn1ActionPerformed

    private void LogBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogBtn2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/restaurant","root","root");
            Statement stmt = con.createStatement();
            int n = Integer.parseInt(TF.getText());
            String LOG = "select * from food_order where day(date) = "+n;
            ResultSet rs = stmt.executeQuery(LOG);

            while (rs.next())
            {
                long A = rs.getLong("Customer_Code");
                String B = rs.getString("Date");
                String C = rs.getString("Time");
                String D = rs.getString("Name");
                String E = rs.getString("Gender");
                String F = rs.getString("EmailId");
                long G = rs.getLong("Contact_No");
                String H = rs.getString("Special_Customer");
                float I = rs.getFloat("Total_Bill");

                Object [] data = { A,B,C,D,E,F,G,H,I } ;
                dtm.addRow(data);
            }
                JOptionPane.showMessageDialog(null,"Customer Log Successfully Searched","Information",1);
            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e,"Error",0);
        }
    }//GEN-LAST:event_LogBtn2ActionPerformed

    private void LogBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogBtn3ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/restaurant","root","root");
            Statement stmt = con.createStatement();
            int n = Integer.parseInt(TF.getText());
            String LOG = "select * from food_order where month(date) = "+n;
            ResultSet rs = stmt.executeQuery(LOG);

            while (rs.next())
            {
                long A = rs.getLong("Customer_Code");
                String B = rs.getString("Date");
                String C = rs.getString("Time");
                String D = rs.getString("Name");
                String E = rs.getString("Gender");
                String F = rs.getString("EmailId");
                long G = rs.getLong("Contact_No");
                String H = rs.getString("Special_Customer");
                float I = rs.getFloat("Total_Bill");

                Object [] data = { A,B,C,D,E,F,G,H,I } ;
                dtm.addRow(data);
            }
                JOptionPane.showMessageDialog(null,"Customer Log Successfully Searched","Information",1);
            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e,"Error",0);
        }
            
        
    }//GEN-LAST:event_LogBtn3ActionPerformed

    private void LogBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogBtn4ActionPerformed
        // TODO add your handling code here:
        SearchMenu SM = new SearchMenu();
        SM.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogBtn4ActionPerformed

    private void TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundLabel;
    private javax.swing.JButton LogBtn;
    private javax.swing.JButton LogBtn1;
    private javax.swing.JButton LogBtn2;
    private javax.swing.JButton LogBtn3;
    private javax.swing.JButton LogBtn4;
    private javax.swing.JButton ReturnBtn;
    private javax.swing.JTextField TF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
